name: 与上游同步分叉

on:
  schedule:
    # - cron: '0 0 * * *'  # 每天自动同步
    - cron: '0 0 1-31/3 * *' # 每3天在UTC时间午夜运行一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: 检查 fork 存储库
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/apache/rocketmq-dashboard.git
        git fetch upstream

    - name: Merge upstream changes into fork
      run: |
        git checkout master
        git merge upstream/master --allow-unrelated-histories

    - name: Push changes to fork
      run: |
        git push origin master
