name: 与上游同步分叉

on:
  schedule:
    # - cron: '0 0 * * *'  # 每天自动同步
    - cron: '0 0 1-31/5 * *' # 每5天在UTC时间午夜运行一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: 检查 fork 存储库
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/apache/rocketmq-dashboard.git
        git fetch upstream

    - name: Merge upstream changes into fork
      run: |
        git checkout master
        # 尝试合并，使用 ours 策略保留 .github/workflows/ 的内容
        git merge upstream/master --allow-unrelated-histories -X ours -- .github/workflows/ || true
        # 检查是否有未解决的冲突
        if git status | grep -q "fix conflicts"; then
          echo "Merge conflicts detected. Keeping fork's workflow files."
          git checkout --ours -- .github/workflows/
          git add .github/workflows/
          git commit -m "Resolve conflicts by keeping fork's workflow files"
        fi

    - name: Push changes to fork
      run: |
        git push origin master
